### ISSUE TITLE
Bug about multiprocessing distributed

### ISSUE THREAD

**Issue by JSHZT** [Doubiiu/CodeTalker#12]
In order to train with 4 graphics cards at the same time, I set a to True and set train_gpu to [0,1,2,3], but I got the following error
```
[2023-04-18 15:43:41,052 INFO train_pred.py line 71 682101]=>=> creating model ...                                                      [195/1825]
Traceback (most recent call last):                                                                                                                
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main                                                     
    return _run_code(code, main_globals, None,                                                                                                    
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 87, in _run_code                                                                
    exec(code, run_globals)                                                                                                                       
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/__main__.py", line 39, in <module>                                        
    cli.main()                                                                                                                                    
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/server/cli.py", line 430, in main                                         
    run()                                                                                                                                         
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/server/cli.py", line 284, in run_file                                     
    runpy.run_path(target, run_name="__main__")                                                                                                   
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path   
    return _run_module_code(code, init_globals, run_name,                                                                                         
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module
_code                                                                                                                                             
    _run_code(code, mod_globals, init_globals,
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "main/train_pred.py", line 259, in <module>
    main()
  File "main/train_pred.py", line 45, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/root/autodl-tmp/hzt/code/CodeTalker/main/train_pred.py", line 120, in main_worker
    loss_train, motion_loss_train, reg_loss_train = train(train_loader, model, loss_fn, optimizer, epoch, cfg)
  File "/root/autodl-tmp/hzt/code/CodeTalker/main/train_pred.py", line 162, in train
    model.autoencoder.eval()
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'autoencoder'
```

**Comment by Doubiiu** [comment]
Hi. 
1. Please refer [issue 5](https://github.com/Doubiiu/CodeTalker/issues/5) for details about 'autoencoder'.
2. Currently, as described at the bottom of README, although the codebase supports multi-GPU training, we trained the model with batch_size=1 and hardcode it (follow FaceFormer). You may need to modify the code (data loader, training script, etc.) to make it workable with multi-GPU training setting. I think the dataset is relatively small and making batch_size equal to 1 is affordable and works well empirically.

**Comment by JSHZT** [comment]
At the same time, I would like to ask you some questions. In order to support batch>1, I used fixed-length data. In addition, based on Faceformer's point of view, I disabled teacher forcing, but I found that the video memory will be greatly increased, and the time consumed will also increase a lot, especially the time of backword. Do you know why, the following is the code I changed
```
def forward(self, audio, vertice, one_hot, init_state, criterion, teacher_forcing=True):
        # tgt_mask: :math:`(T, T)`.
        # memory_mask: :math:`(T, S)`.
        init_state = init_state.unsqueeze(1) # (1,1,V*3)
        # style embedding
        obj_embedding = self.learnable_style_emb(torch.argmax(one_hot, dim=1))
        obj_embedding = obj_embedding.unsqueeze(1)
        frame_num = vertice.shape[1]
        # audio feature extraction
        hidden_states = self.audio_encoder(audio, self.dataset, frame_num=frame_num).last_hidden_state
        if self.dataset == "BIWI":
            if hidden_states.shape[1]<frame_num*2:
                vertice = vertice[:, :hidden_states.shape[1]//2]
                frame_num = hidden_states.shape[1]//2
        hidden_states = self.audio_feature_map(hidden_states)
        # gt motion feature extraction
        # feat_q_gt, _ = self.autoencoder.get_quant(vertice - template)
        feat_q_gt, _ = self.autoencoder.get_quant(vertice)
        feat_q_gt = feat_q_gt.permute(0,2,1)
        # autoregressive facial motion prediction with teacher-forcing
        if teacher_forcing:
            vertice_emb = obj_embedding 
            style_emb = vertice_emb  
            vertice_input = torch.cat((init_state,vertice[:,:-1]), 1) # shift one position
            # vertice_input = vertice_input - template
            vertice_input = self.vertice_map(vertice_input)
            vertice_input = vertice_input + style_emb
            vertice_input = self.PPE(vertice_input)
            tgt_mask = self.biased_mask[:, :vertice_input.shape[1], :vertice_input.shape[1]].clone().detach().to(device=self.device)
            tgt_mask = tgt_mask.repeat(vertice_input.shape[0], 1, 1)
            memory_mask = enc_dec_mask(self.device, self.dataset, vertice_input.shape[1], hidden_states.shape[1])
            feat_out = self.transformer_decoder(vertice_input, hidden_states, tgt_mask=tgt_mask, memory_mask=memory_mask)
            feat_out = self.feat_map(feat_out)
            feat_out = feat_out.reshape(feat_out.shape[0], feat_out.shape[1]*self.args.face_quan_num, -1)
            # feature quantization
            feat_out_q, _, _ = self.autoencoder.quantize(feat_out)
            # feature decoding
            vertice_out = self.autoencoder.decode(feat_out_q)
            # vertice_out = vertice_out + template
        else:
            for i in range(frame_num):
                if i==0:
                    vertice_emb = obj_embedding # (1,1,feature_dim)
                    style_emb = vertice_emb
                    input = self.vertice_map(init_state)
                    input = style_emb + input
                    vertice_input = self.PPE(input)
                else:
                    vertice_input = self.PPE(vertice_emb)
                tgt_mask = self.biased_mask[:, :vertice_input.shape[1], :vertice_input.shape[1]].clone().detach().to(device=self.device)
                tgt_mask = tgt_mask.repeat(vertice_input.shape[0], 1, 1)
                memory_mask = enc_dec_mask(self.device, self.dataset, vertice_input.shape[1], hidden_states.shape[1])
                feat_out = self.transformer_decoder(vertice_input, hidden_states, tgt_mask=tgt_mask, memory_mask=memory_mask)
                feat_out = self.feat_map(feat_out)
                feat_out = feat_out.reshape(feat_out.shape[0], feat_out.shape[1]*self.args.face_quan_num, -1)
                # predicted feature to quantized one
                feat_out_q, _, _ = self.autoencoder.quantize(feat_out)
                # quantized feature to vertice
                if i == 0:
                    vertice_out_q = self.autoencoder.decode(torch.cat([feat_out_q, feat_out_q], dim=-1))
                    vertice_out_q = vertice_out_q[:,0].unsqueeze(1)
                else:
                    vertice_out_q = self.autoencoder.decode(feat_out_q)
                if i != frame_num - 1:
                    new_output = self.vertice_map(vertice_out_q[:,-1,:]).unsqueeze(1)
                    new_output = new_output + style_emb
                    vertice_emb = torch.cat((vertice_emb, new_output), 1)
            feat_out_q, _, _ = self.autoencoder.quantize(feat_out)
            vertice_out = self.autoencoder.decode(feat_out_q)
        # loss 
        loss_motion = criterion(vertice_out, vertice) # (batch, seq_len, V*3)
        loss_reg = criterion(feat_out, feat_q_gt.detach())

        return self.args.motion_weight*loss_motion + self.args.reg_weight*loss_reg, [loss_motion, loss_reg]

```

**Comment by JSHZT** [comment]
> 

I confirm that I have explicitly specified which python file to execute in the shell script

**Comment by xiapengchng** [comment]
Do you solve the problem?  When training without teacheforcing, i find it's too slow, 100 epch needs 100h?

**Comment by JSHZT** [comment]
> Do you solve the problem? When training without teacheforcing, i find it's too slow, 100 epch needs 100h?

Sorry, no, according to my statistics, the slow speed is caused by the special structure of VQVAE, and the gradient will be particularly slow in backword. Because of this, I plan to try to use Doka training to reduce the time required for training.

**Comment by 541979210** [comment]
> 

Are there any updates to the question you metioned?
its really slow in my experiments when I set teacher_forcing False.

**Comment by JSHZT** [comment]
Sorry for the late reply. After a lot of attempts in different tasks, the autoregressive training method is very slow, especially the number of layers used in this task is 6 layers. When the number of layers is changed to 1 layer, the training speed will be very fast, but will not perform as well
